'use strict';
(()=>{
const $=id=>document.getElementById(id),states=['بانتظار التحميل','بالطريق','بانتظار التخليص','تم التسليم'];
const token=new URLSearchParams(location.search).get('trip')||new URLSearchParams(location.hash.slice(1)).get('driver')||'';
let gps=null,ready=false;
const stamp=t=>new Intl.DateTimeFormat('ar-SY',{timeZone:'Asia/Damascus',dateStyle:'short',timeStyle:'short'}).format(new Date(t));
function errorText(e){return e.name==='AbortError'?'الاتصال تأخر. تحقق من الإنترنت واضغط إعادة المحاولة.':/fetch|network|load failed/i.test(e.message)?'تعذّر الاتصال بخدمة الرحلات. تحقق من الإنترنت وحاول مجدداً.':e.message||'تعذّر فتح الرحلة';}
async function api(action,body={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),25000);try{const r=await fetch('https://ymkzrzdmdrqllpvqdlfx.supabase.co/functions/v1/fleet-api',{method:'POST',headers:{'Content-Type':'application/json',apikey:'sb_publishable_NnABPXhnEsU9-jVgp6DhRQ_Fl-c1xRH'},body:JSON.stringify({action,token,...body}),signal:c.signal});let data;try{data=await r.json();}catch{throw new Error('تعذّر قراءة رد خدمة الرحلات؛ أعد المحاولة');}if(!r.ok||data.error)throw new Error(data.error||'تعذّر تنفيذ الطلب');return data;}finally{clearTimeout(timer);}}
async function loadTrip(){ready=false;$('locateDriver').disabled=true;$('sendDriver').disabled=true;$('retryDriver').hidden=true;$('driverResult').textContent='';if(!/^[a-f0-9]{64}$/.test(token)){$('driverPlate').textContent='الرابط غير مكتمل';$('driverResult').textContent='اطلب من المكتب رابط السيارة كاملاً؛ رابط الصفحة وحده لا يحدد الرحلة.';return;}try{const info=await api('driverInfo');$('driverPlate').textContent='السيارة '+info.plate;$('driverCompany').textContent=info.company;$('driverDestination').textContent='الوجهة: '+(info.destination||'غير محدّدة');$('driverState').replaceChildren(...states.map(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;return o;}));$('driverState').value=info.status;ready=true;$('locateDriver').disabled=false;}catch(e){$('driverPlate').textContent='تعذّر فتح الرحلة';$('driverResult').textContent=errorText(e);$('retryDriver').hidden=false;}}
$('retryDriver').onclick=loadTrip;
$('locateDriver').onclick=()=>{if(!ready)return;if(!navigator.geolocation){$('gpsStatus').textContent='افتح الرابط في Safari أو Chrome لتحديد الموقع';return;}gps=null;$('sendDriver').disabled=true;$('locateDriver').disabled=true;$('driverResult').textContent='';$('driverPlace').value='';$('gpsStatus').textContent='وافق على إذن الموقع؛ جارٍ تحديد مكانك…';navigator.geolocation.getCurrentPosition(async p=>{const current={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,time:Date.now()};gps=current;$('gpsStatus').textContent='تم تحديد الموقع بدقة تقارب '+Math.round(current.accuracy)+' متر. جارٍ معرفة اسم البلدة…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+current.latitude+'&longitude='+current.longitude+'&localityLanguage=ar',{signal:controller.signal});if(!r.ok)throw new Error();const d=await r.json();const place=[...new Set([d.locality||d.city,d.principalSubdivision,d.countryName].filter(Boolean))].join(' — ');if(!place)throw new Error();$('driverPlace').value=place;$('gpsStatus').textContent='موقعك جاهز. راجع اسم البلدة ثم أرسل التحديث.';}catch{$('gpsStatus').textContent='تم تحديد الإحداثيات؛ اكتب اسم البلدة قبل الإرسال.';}finally{clearTimeout(timer);$('locateDriver').disabled=false;$('sendDriver').disabled=false;}},e=>{$('gpsStatus').textContent=e.code===1?'إذن الموقع مرفوض. فعّله للموقع من إعدادات المتصفح، ثم حاول مجدداً.':'تعذّر تحديد الموقع؛ فعّل خدمة الموقع وحاول مجدداً.';$('locateDriver').disabled=false;},{enableHighAccuracy:true,timeout:20000,maximumAge:0});};
$('sendDriver').onclick=async()=>{if(!ready||!gps||Date.now()-gps.time>300000){$('driverResult').textContent='حدّد موقعك من جديد قبل الإرسال';return;}const place=$('driverPlace').value.trim();if(!place){$('driverResult').textContent='اكتب اسم المكان أولاً';return;}$('sendDriver').disabled=true;try{const r=await api('driverUpdate',{latitude:gps.latitude,longitude:gps.longitude,accuracy:gps.accuracy,place,status:$('driverState').value,note:$('driverNote').value});$('driverResult').textContent='✓ وصل التحديث إلى المكتب — '+stamp(r.time);gps=null;$('gpsStatus').textContent='تم الإرسال. حدّد موقعك من جديد عندما تريد إرسال تحديث آخر.';}catch(e){$('driverResult').textContent=errorText(e);$('sendDriver').disabled=false;}};
loadTrip();
})();
