'use strict';
(()=>{
const $=id=>document.getElementById(id),states=['بانتظار التحميل','بالطريق','بانتظار التخليص','تم التسليم'];
let tripId='',gps=null,ready=false,epoch=0;
const db=window.supabase.createClient('https://ymkzrzdmdrqllpvqdlfx.supabase.co','sb_publishable_NnABPXhnEsU9-jVgp6DhRQ_Fl-c1xRH',{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'khotwati-driver-session'}});
const stamp=t=>new Intl.DateTimeFormat('ar-SY',{timeZone:'Asia/Damascus',dateStyle:'short',timeStyle:'short'}).format(new Date(t));
function errorText(e){return e.name==='AbortError'?'الاتصال تأخر. تحقق من الإنترنت واضغط إعادة المحاولة.':/fetch|network|load failed/i.test(e.message)?'تعذّر الاتصال بخدمة الرحلات. تحقق من الإنترنت وحاول مجدداً.':e.message||'تعذّر فتح الرحلة';}
async function api(action,body={}){const c=new AbortController(),timer=setTimeout(()=>c.abort(),25000);try{const {data:{session}}=await db.auth.getSession();if(!session){showLogin();throw new Error('سجّل الدخول أولاً');}const r=await fetch('https://ymkzrzdmdrqllpvqdlfx.supabase.co/functions/v1/fleet-api',{method:'POST',headers:{Authorization:'Bearer '+session.access_token,'Content-Type':'application/json',apikey:'sb_publishable_NnABPXhnEsU9-jVgp6DhRQ_Fl-c1xRH'},body:JSON.stringify({action,trip_id:tripId,...body}),signal:c.signal});let data;try{data=await r.json();}catch{throw new Error('تعذّر قراءة رد خدمة الرحلات؛ أعد المحاولة');}if(r.status===401)showLogin();if(!r.ok||data.error)throw new Error(data.error||'تعذّر تنفيذ الطلب');return data;}finally{clearTimeout(timer);}}
async function loadTrip(){const version=++epoch;gps=null;ready=false;$('locateDriver').disabled=true;$('sendDriver').disabled=true;$('retryDriver').hidden=true;$('driverResult').textContent='';if(!tripId)return;try{const info=await api('driverInfo');if(version!==epoch)return;$('driverPlate').textContent='السيارة '+info.plate;$('driverCompany').textContent=info.company;$('driverDestination').textContent='الوجهة: '+(info.destination||'غير محدّدة');$('driverState').replaceChildren(...states.map(s=>{const o=document.createElement('option');o.value=s;o.textContent=s;return o;}));$('driverState').value=info.status;ready=true;$('locateDriver').disabled=false;}catch(e){$('driverPlate').textContent='تعذّر فتح الرحلة';$('driverResult').textContent=errorText(e);$('retryDriver').hidden=false;}}
$('retryDriver').onclick=loadTrip;
$('locateDriver').onclick=()=>{if(!ready)return;const version=epoch;if(!navigator.geolocation){$('gpsStatus').textContent='افتح الرابط في Safari أو Chrome لتحديد الموقع';return;}gps=null;$('sendDriver').disabled=true;$('locateDriver').disabled=true;$('driverResult').textContent='';$('driverPlace').value='';$('gpsStatus').textContent='وافق على إذن الموقع؛ جارٍ تحديد مكانك…';navigator.geolocation.getCurrentPosition(async p=>{if(version!==epoch)return;const current={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,time:Date.now()};gps=current;$('gpsStatus').textContent='تم تحديد الموقع بدقة تقارب '+Math.round(current.accuracy)+' متر. جارٍ معرفة اسم البلدة…';const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);try{const r=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+current.latitude+'&longitude='+current.longitude+'&localityLanguage=ar',{signal:controller.signal});if(!r.ok)throw new Error();const d=await r.json();if(version!==epoch)return;const place=[...new Set([d.locality||d.city,d.principalSubdivision,d.countryName].filter(Boolean))].join(' — ');if(!place)throw new Error();$('driverPlace').value=place;$('gpsStatus').textContent='موقعك جاهز. راجع اسم البلدة ثم أرسل التحديث.';}catch{if(version!==epoch)return;$('gpsStatus').textContent='تم تحديد الإحداثيات؛ اكتب اسم البلدة قبل الإرسال.';}finally{clearTimeout(timer);if(version!==epoch)return;$('locateDriver').disabled=false;$('sendDriver').disabled=false;}},e=>{if(version!==epoch)return;$('gpsStatus').textContent=e.code===1?'إذن الموقع مرفوض. فعّله للموقع من إعدادات المتصفح، ثم حاول مجدداً.':'تعذّر تحديد الموقع؛ فعّل خدمة الموقع وحاول مجدداً.';$('locateDriver').disabled=false;},{enableHighAccuracy:true,timeout:20000,maximumAge:0});};
$('sendDriver').onclick=async()=>{if(!ready||!gps||Date.now()-gps.time>300000){$('driverResult').textContent='حدّد موقعك من جديد قبل الإرسال';return;}const place=$('driverPlace').value.trim();if(!place){$('driverResult').textContent='اكتب اسم المكان أولاً';return;}$('sendDriver').disabled=true;try{const r=await api('driverUpdate',{latitude:gps.latitude,longitude:gps.longitude,accuracy:gps.accuracy,place,status:$('driverState').value,note:$('driverNote').value});$('driverResult').textContent='✓ وصل التحديث إلى المكتب — '+stamp(r.time);gps=null;$('gpsStatus').textContent='تم الإرسال. حدّد موقعك من جديد عندما تريد إرسال تحديث آخر.';}catch(e){$('driverResult').textContent=errorText(e);$('sendDriver').disabled=false;}};
function showLogin(){epoch++;ready=false;gps=null;$('driverLogin').hidden=false;$('driverPage').hidden=true;$('driverChooser').hidden=true;$('driverLogout').hidden=true;}
async function loadAccount(){
 const {data:{session}}=await db.auth.getSession();if(!session){showLogin();return;}
 $('driverLogin').hidden=true;$('driverLogout').hidden=false;$('driverChooser').hidden=false;
 $('driverAccountStatus').textContent='جارٍ تحميل رحلاتك…';$('driverPage').hidden=true;ready=false;gps=null;
 try{
  const data=await api('driverTrips');
  $('driverTrips').replaceChildren(...data.trips.map(t=>{const o=document.createElement('option');o.value=t.id;o.textContent=t.plate+' — '+(t.destination||'بدون وجهة');return o;}));
  $('driverAccountStatus').textContent=data.company+' · '+data.username+(data.trips.length?'':' — لا توجد رحلات مفتوحة مرتبطة بحسابك. تواصل مع المكتب.');
  tripId=data.trips.some(t=>t.id===tripId)?tripId:(data.trips[0]?.id||'');$('driverTrips').value=tripId;
  if(tripId){$('driverPage').hidden=false;await loadTrip();}
 }catch(e){$('driverAccountStatus').textContent=errorText(e);throw e;}
}
$('driverLoginForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('driverLoginError').textContent='';try{
 const {error}=await db.auth.signInWithPassword({email:$('driverUsername').value.trim().toLowerCase()+'@nahda-fleet.invalid',password:$('driverPassword').value});if(error)throw error;
 $('driverPassword').value='';await loadAccount();
}catch(e){if(!$('driverLogin').hidden){$('driverLoginError').textContent=/Invalid login/i.test(e.message)?'اسم المستخدم أو كلمة المرور غير صحيحة':errorText(e);}}finally{button.disabled=false;}};
$('driverLogout').onclick=async()=>{const {error}=await db.auth.signOut({scope:'local'});if(error){$('driverAccountStatus').textContent=errorText(error);return;}tripId='';showLogin();};
$('reloadTrips').onclick=()=>loadAccount().catch(()=>{});
$('driverTrips').onchange=()=>{tripId=$('driverTrips').value;gps=null;$('driverPlace').value='';$('driverNote').value='';$('gpsStatus').textContent='';loadTrip();};
loadAccount().catch(()=>{});
})();
