'use strict';
const t=window.KhotwatiI18n.t,locale=window.KhotwatiI18n.locale;
const URL_DB='https://ymkzrzdmdrqllpvqdlfx.supabase.co',KEY='sb_publishable_NnABPXhnEsU9-jVgp6DhRQ_Fl-c1xRH';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const states=['بانتظار التحميل','بالطريق','بانتظار التخليص','تم التسليم'];
const day=t=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Damascus',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(t));
const stamp=t=>t?new Intl.DateTimeFormat(locale,{timeZone:'Asia/Damascus',dateStyle:'short',timeStyle:'short'}).format(new Date(t)):window.KhotwatiI18n.t('لم يصل تحديث');
let db,me,companies=[],trips=[],members=[],reportRows=[],reportReady=false,driverToken='',gps=null,reportTitle='';
function toast(text){$('toast').textContent=text;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,6500);}
function root(){return me?.role==='super_admin';}
function errorText(e){const s=e?.message||String(e);if(/Invalid login/i.test(s))return window.KhotwatiI18n.t('اسم المستخدم أو كلمة المرور غير صحيحة');if(/rate limit|too many/i.test(s))return window.KhotwatiI18n.t('محاولات كثيرة؛ انتظر قليلاً ثم أعد المحاولة');if(/fetch|network/i.test(s))return window.KhotwatiI18n.t('تعذّر الاتصال. تحقق من الإنترنت ثم أعد المحاولة');return window.KhotwatiI18n.t(s);}
async function api(action,body={}){const {data:{session}}=await db.auth.getSession();const r=await fetch(URL_DB+'/functions/v1/fleet-api',{method:'POST',headers:{'Content-Type':'application/json',apikey:KEY,...(session?{Authorization:'Bearer '+session.access_token}:{})},body:JSON.stringify({action,...body})});const result=await r.json();if(!r.ok||result.error)throw new Error(result.error||window.KhotwatiI18n.t('تعذّر تنفيذ العملية'));return result;}
async function checked(p){const r=await p;if(r.error)throw r.error;return r.data;}
async function all(table,select='*'){let out=[];for(let start=0;;start+=500){const rows=await checked(db.from(table).select(select).order(table==='fleet_memberships'?'user_id':'id').range(start,start+499));out.push(...rows);if(rows.length<500)return out;}}
function modal(title,html){$('modalTitle').textContent=title;$('modalContent').innerHTML=html;$('modalError').textContent='';$('modal').showModal();}
function formHandler(id,fn){$(id).onsubmit=async e=>{e.preventDefault();const btn=e.submitter;btn.disabled=true;$('modalError').textContent='';try{await fn(new FormData(e.target));}catch(err){$('modalError').textContent=errorText(err);}finally{btn.disabled=false;}};}
const field=(name,label,type='text',extra='')=>'<div><label for="f_'+name+'">'+label+'</label><input id="f_'+name+'" name="'+name+'" type="'+type+'" '+extra+'></div>';
const options=(values,chosen)=>values.map(v=>'<option value="'+esc(v)+'" '+(v===chosen?'selected':'')+'>'+esc(window.KhotwatiI18n.t(v))+'</option>').join('');
function companyName(id){return companies.find(c=>c.id===id)?.name||'—';}
function visibleTrips(){return trips.filter(t=>(!$('companyFilter').value||t.company_id===$('companyFilter').value)&&($('tripFilter').value==='all'||t.closed===($('tripFilter').value==='closed'))&&[t.plate,t.driver,t.destination].join(' ').toLowerCase().includes($('search').value.toLowerCase()));}
async function load(){const uid=(await db.auth.getUser()).data.user?.id;if(!uid)throw new Error(window.KhotwatiI18n.t('سجّل الدخول مجدداً'));me=await checked(db.from('fleet_memberships').select('*').eq('user_id',uid).maybeSingle());if(!me?.active)throw new Error(window.KhotwatiI18n.t('هذا الحساب غير مفعّل؛ تواصل مع المدير العام'));[companies,trips]=await Promise.all([all('fleet_companies'),all('fleet_trip_status')]);if(!root()&&!companies.some(c=>c.id===me.company_id&&c.active))throw new Error(window.KhotwatiI18n.t('حساب الشركة موقوف؛ تواصل مع المدير العام'));members=root()?await all('fleet_memberships'):[];companies.sort((a,b)=>a.name.localeCompare(b.name,'ar'));trips.sort((a,b)=>new Date(b.created_at)-new Date(a.created_at));$('login').hidden=true;$('office').hidden=false;$('accountBar').hidden=false;$('accountName').textContent=me.username;$('roleLabel').textContent=root()?window.KhotwatiI18n.t('المدير العام / كل الشركات'):window.KhotwatiI18n.t('لوحة الشركة');$('heading').textContent=root()?window.KhotwatiI18n.t('غرفة متابعة الشركات'):companyName(me.company_id);$('companiesTab').hidden=!root();$('dateLabel').textContent=new Intl.DateTimeFormat(locale,{dateStyle:'full',timeZone:'Asia/Damascus'}).format(new Date())+window.KhotwatiI18n.t(' · توقيت دمشق');['companyFilter','reportCompany'].forEach(id=>{const old=$(id).value;$(id).innerHTML=(root()?window.KhotwatiI18n.t('<option value="">كل الشركات</option>'):'')+companies.map(c=>'<option value="'+c.id+'">'+esc(c.name)+(c.active?'':window.KhotwatiI18n.t(' — موقوفة'))+'</option>').join('');if(companies.some(c=>c.id===old)||root()&&old==='')$(id).value=old;});render();$('syncTime').textContent=window.KhotwatiI18n.t('آخر جلب: ')+stamp(Date.now());}
function render(){const open=trips.filter(t=>!t.closed);$('countCompanies').textContent=companies.length.toLocaleString(locale);$('countTrips').textContent=open.length.toLocaleString(locale);const fresh=open.filter(t=>t.last_update&&day(t.last_update)===day(Date.now())).length;$('countFresh').textContent=fresh.toLocaleString(locale);$('countStale').textContent=(open.length-fresh).toLocaleString(locale);const list=visibleTrips();$('tripsList').innerHTML=list.length?list.map(t=>'<article class="trip"><div><h3>'+esc(t.plate)+'</h3><small>'+esc(companyName(t.company_id))+window.KhotwatiI18n.t('</small><small>السائق: ')+esc(t.driver||window.KhotwatiI18n.t('غير محدّد'))+'</small></div><div><b>'+esc(t.place||window.KhotwatiI18n.t('لا يوجد موقع بعد'))+'</b><small class="'+(!t.last_update||day(t.last_update)!==day(Date.now())?'old':'')+'">'+esc(stamp(t.last_update))+window.KhotwatiI18n.t('</small><small>الوجهة: ')+esc(t.destination||'—')+'</small></div><div><span class="status">'+esc(window.KhotwatiI18n.t(t.status))+'</span><small>'+esc(t.note||'')+'</small>'+(t.closed?window.KhotwatiI18n.t('<small>رحلة مغلقة</small>'):'')+'</div><div class="actions"><button class="secondary" data-op="history" data-id="'+t.id+window.KhotwatiI18n.t('">السجل</button><button class="secondary" data-op="share" data-id="')+t.id+window.KhotwatiI18n.t('">واتساب</button>')+(!t.closed?'<button class="primary" data-op="link" data-id="'+t.id+window.KhotwatiI18n.t('">إنشاء / إدارة حساب السائق</button><button class="secondary" data-op="update" data-id="')+t.id+window.KhotwatiI18n.t('">تحديث مكتبي</button><button class="danger" data-op="close" data-id="')+t.id+window.KhotwatiI18n.t('">إغلاق الرحلة</button>'):'')+'</div></article>').join(''):window.KhotwatiI18n.t('<div class="empty">لا توجد رحلات هنا بعد. ')+(root()&&!companies.length?window.KhotwatiI18n.t('أضف أول شركة من «الشركات والحسابات».'):window.KhotwatiI18n.t('اضغط «إضافة رحلة» لتبدأ.'))+'</div>';$('companiesList').innerHTML=companies.length?companies.map(c=>'<article class="company-card"><div><h3>'+esc(c.name)+window.KhotwatiI18n.t('</h3><p class="muted">أدمن: ')+esc(members.find(m=>m.company_id===c.id)?.username||'—')+' · '+trips.filter(t=>t.company_id===c.id&&!t.closed).length+window.KhotwatiI18n.t(' رحلات مفتوحة</p><span class="tag">')+(c.active?window.KhotwatiI18n.t('فعّالة'):window.KhotwatiI18n.t('موقوفة'))+'</span></div><div class="actions"><button class="secondary" data-company="'+c.id+window.KhotwatiI18n.t('" data-action="reset">إعادة تعيين كلمة المرور</button><button class="secondary" data-company="')+c.id+'" data-action="toggle">'+(c.active?window.KhotwatiI18n.t('إيقاف الشركة'):window.KhotwatiI18n.t('تفعيل الشركة'))+'</button></div></article>').join(''):window.KhotwatiI18n.t('<div class="empty">أضف شركة وحدّد اسم مستخدم وكلمة مرور لأدمنها.</div>');}
function switchTab(tab){['trips','reports','companies'].forEach(t=>{$(t+'Panel').hidden=t!==tab;document.querySelector('[data-tab="'+t+'"]').classList.toggle('active',t===tab);});if(tab==='reports'&&!reportReady)makeReport().catch(e=>toast(errorText(e)));}
function singleMessage(t){return [window.KhotwatiI18n.t('تحديث حركة سيارة'),window.KhotwatiI18n.t('الشركة: ')+companyName(t.company_id),window.KhotwatiI18n.t('رقم السيارة: ')+t.plate,window.KhotwatiI18n.t('الموقع: ')+(t.place||window.KhotwatiI18n.t('لم يصل موقع بعد')),window.KhotwatiI18n.t('الحالة: ')+window.KhotwatiI18n.t(t.status),window.KhotwatiI18n.t('آخر تحديث: ')+stamp(t.last_update),t.last_update&&day(t.last_update)!==day(Date.now())?window.KhotwatiI18n.t('⚠ الموقع قديم؛ لم يصل تحديث اليوم'):'',t.note?window.KhotwatiI18n.t('ملاحظة: ')+t.note:'',t.latitude!=null?'https://www.google.com/maps?q='+t.latitude+','+t.longitude:''].filter(Boolean).join('\n');}
async function copy(text){try{await navigator.clipboard.writeText(text);toast(window.KhotwatiI18n.t('تم النسخ'));}catch{toast(window.KhotwatiI18n.t('تعذّر النسخ التلقائي؛ حدّد النص وانسخه يدوياً.'));}}
function tripAction(op,id){const t=trips.find(x=>x.id===id);if(!t)return;if(op==='share'){const text=singleMessage(t);modal(window.KhotwatiI18n.t('رسالة السيارة'),'<textarea id="singleText" readonly rows="9">'+esc(text)+'</textarea><div class="actions"><a class="wa" href="https://wa.me/?text='+encodeURIComponent(text)+window.KhotwatiI18n.t('" target="_blank" rel="noopener noreferrer">فتح واتساب ↗</a><button id="copySingle" class="secondary">نسخ</button></div>'));$('copySingle').onclick=()=>copy(text);}
 if(op==='link'){driverAccount(t).catch(e=>{$('modalError').textContent=errorText(e);});}
 if(op==='update'){modal(window.KhotwatiI18n.t('تحديث مكتبي · ')+t.plate,'<form id="updateForm">'+field('place',window.KhotwatiI18n.t('مكان السيارة'),'text',window.KhotwatiI18n.t('required maxlength="200" placeholder="مثال: سرمدا — إدلب"'))+window.KhotwatiI18n.t('<label for="f_status">الحالة</label><select id="f_status" name="status">')+options(states,t.status)+window.KhotwatiI18n.t('</select><label for="f_note">ملاحظة</label><textarea id="f_note" name="note" maxlength="500"></textarea><p class="muted">يُحفظ كمعلومة من المكتب، وليس موقع GPS من السائق.</p><button class="primary wide">حفظ التحديث</button></form>'));formHandler('updateForm',async f=>{await api('officeUpdate',{trip_id:id,...Object.fromEntries(f)});$('modal').close();await load();reportReady=false;toast(window.KhotwatiI18n.t('تم حفظ التحديث'));});}
 if(op==='close'){modal(window.KhotwatiI18n.t('إغلاق رحلة ')+t.plate,window.KhotwatiI18n.t('<p>سيُوقف رابط السائق وتبقى التحديثات محفوظة بالسجل.</p><button id="confirmClose" class="primary wide">تأكيد إغلاق الرحلة</button>'));$('confirmClose').onclick=async()=>{try{await api('closeTrip',{trip_id:id});$('modal').close();await load();}catch(e){$('modalError').textContent=errorText(e);}};}
 if(op==='history'){modal(window.KhotwatiI18n.t('سجل السيارة ')+t.plate,window.KhotwatiI18n.t('<p>جارٍ تحميل آخر ١٠٠ تحديث…</p>'));checked(db.from('fleet_updates').select('*').eq('trip_id',id).order('created_at',{ascending:false}).limit(100)).then(rows=>{$('modalContent').innerHTML=rows.length?'<div class="timeline">'+rows.map(u=>'<article><b>'+esc(u.place)+'</b><p>'+esc(window.KhotwatiI18n.t(u.status))+' · '+esc(u.note)+'</p><small>'+esc(stamp(u.created_at))+' · '+(u.source==='driver'?window.KhotwatiI18n.t('السائق'):window.KhotwatiI18n.t('المكتب'))+'</small>'+(u.latitude!=null?'<p><a target="_blank" rel="noopener noreferrer" href="https://www.google.com/maps?q='+u.latitude+','+u.longitude+window.KhotwatiI18n.t('">عرض الموقع على الخريطة ↗</a></p>'):'')+'</article>').join('')+'</div>':window.KhotwatiI18n.t('<div class="empty">لم يصل تحديث لهذه الرحلة بعد.</div>');}).catch(e=>$('modalError').textContent=errorText(e));}
}
async function driverAccount(t){
 modal(window.KhotwatiI18n.t('حساب السائق · ')+t.plate,window.KhotwatiI18n.t('<p>جارٍ تحميل الحسابات…</p>'));
 const data=await api('driverAccountInfo',{trip_id:t.id}),url=location.origin+'/driver.html';
 const assigned=data.drivers.find(d=>d.user_id===data.assigned);
 modal(window.KhotwatiI18n.t('حساب السائق · ')+t.plate,window.KhotwatiI18n.t('<p>الحساب المرتبط: <b>')+esc(assigned?.username||window.KhotwatiI18n.t('لم يتم الربط بعد'))+window.KhotwatiI18n.t('</b></p><p>يستخدم السائق نفس الحساب لرحلاته لدى هذه الشركة، ويُحفظ دخوله على متصفحه.</p>')+(data.drivers.length?window.KhotwatiI18n.t('<form id="assignDriverForm"><label>ربط حساب موجود</label><select name="driver_id">')+data.drivers.map(d=>'<option value="'+d.user_id+'" '+(d.user_id===data.assigned?'selected':'')+'>'+esc(d.username)+'</option>').join('')+window.KhotwatiI18n.t('</select><button class="secondary wide">ربط بالرحلة</button></form>'):'')+window.KhotwatiI18n.t('<section class="driver-create"><h3>إنشاء حساب سائق جديد</h3><form id="createDriverForm">')+field('username',window.KhotwatiI18n.t('اسم مستخدم السائق'),'text','required pattern="[a-zA-Z][a-zA-Z0-9_.-]{2,39}" dir="ltr" autocomplete="off"')+field('password',window.KhotwatiI18n.t('كلمة المرور (٦ خانات أو أكثر — أرقام أو أحرف)'),'password','required minlength="6" maxlength="128" autocomplete="new-password"')+window.KhotwatiI18n.t('<button class="primary wide">إنشاء الحساب وربطه بالرحلة</button></form></section>')+(assigned?window.KhotwatiI18n.t('<details><summary>تعيين كلمة مرور جديدة للسائق</summary><form id="resetDriverForm">')+field('password',window.KhotwatiI18n.t('كلمة مرور جديدة'),'password','required minlength="6" maxlength="128" autocomplete="new-password"')+window.KhotwatiI18n.t('<button class="secondary wide">حفظ كلمة المرور</button></form></details>'):'')+window.KhotwatiI18n.t('<p>رابط دخول السائق:</p><div class="link-box">')+esc(url)+window.KhotwatiI18n.t('</div><div class="actions"><button id="copyDriverUrl" class="secondary">نسخ الرابط</button><a class="wa" target="_blank" rel="noopener noreferrer" href="https://wa.me/?text=')+encodeURIComponent(window.KhotwatiI18n.t('خطواتي — دخول السائق')+(assigned?window.KhotwatiI18n.t('\nاسم المستخدم: ')+assigned.username:'')+'\n'+url)+window.KhotwatiI18n.t('">مشاركة الرابط عبر واتساب</a></div><p class="muted">أعطِ السائق كلمة المرور بشكل خاص. لا تظهر كلمات المرور المحفوظة هنا.</p>'));
 $('copyDriverUrl').onclick=()=>copy(url);
 if(data.drivers.length)formHandler('assignDriverForm',async f=>{await api('assignDriver',{trip_id:t.id,driver_id:f.get('driver_id')});await driverAccount(t);toast(window.KhotwatiI18n.t('تم ربط السائق'));});
 formHandler('createDriverForm',async f=>{await api('createDriver',{trip_id:t.id,...Object.fromEntries(f)});await driverAccount(t);toast(window.KhotwatiI18n.t('تم إنشاء حساب السائق وربطه'));});
 if(assigned)formHandler('resetDriverForm',async f=>{await api('resetDriverPassword',{trip_id:t.id,password:f.get('password')});$('modal').close();toast(window.KhotwatiI18n.t('تم تغيير كلمة مرور السائق'));});
}
async function makeReport(){const date=$('reportDate').value;if(!date)throw new Error(window.KhotwatiI18n.t('اختر تاريخ التقرير'));const company=$('reportCompany').value;reportRows=await checked(db.rpc('fleet_report',{p_day:date,p_company:company||null}));reportTitle=window.KhotwatiI18n.t('تقرير حركة السيارات — ')+date+'\n'+(company?companyName(company):window.KhotwatiI18n.t('كل الشركات'));const text=[reportTitle,...reportRows.map((t,i)=>(i+1)+'. '+t.plate+' | '+companyName(t.company_id)+window.KhotwatiI18n.t('\nالموقع: ')+(t.place||window.KhotwatiI18n.t('لا يوجد تحديث'))+' | '+window.KhotwatiI18n.t(t.status)+window.KhotwatiI18n.t('\nآخر تحديث: ')+stamp(t.last_update)+(t.last_update&&day(t.last_update)!==date?window.KhotwatiI18n.t(' ⚠ موقع قديم'):'')+(t.note?window.KhotwatiI18n.t('\nملاحظة: ')+t.note:''))].join('\n\n');$('reportText').value=text;$('reportWhatsApp').href='https://wa.me/?text='+encodeURIComponent(text);$('reportTable').innerHTML='<h3>'+esc(reportTitle).replace('\n',' · ')+'</h3>'+(reportRows.length?window.KhotwatiI18n.t('<div class="table-wrap"><table><thead><tr><th>الشركة / السيارة</th><th>المكان</th><th>الحالة</th><th>آخر تحديث</th></tr></thead><tbody>')+reportRows.map(t=>'<tr><td>'+esc(companyName(t.company_id))+'<br>'+esc(t.plate)+'</td><td>'+esc(t.place||window.KhotwatiI18n.t('لا يوجد تحديث'))+'</td><td>'+esc(window.KhotwatiI18n.t(t.status))+'</td><td>'+esc(stamp(t.last_update))+(t.last_update&&day(t.last_update)!==date?window.KhotwatiI18n.t('<br>⚠ موقع قديم'):'')+'</td></tr>').join('')+'</tbody></table></div>':window.KhotwatiI18n.t('<div class="empty">لا توجد رحلات لهذا التاريخ.</div>'));reportReady=true;}
function bind(){
 $('closeModal').onclick=()=>$('modal').close();$('reportDate').value=day(Date.now());$('reportDate').max=day(Date.now());
 document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>switchTab(b.dataset.tab));['companyFilter','tripFilter'].forEach(id=>$(id).onchange=render);$('search').oninput=render;
 $('refresh').onclick=async()=>{try{await load();reportReady=false;toast(window.KhotwatiI18n.t('تم تحديث البيانات'));}catch(e){toast(errorText(e));}};
 $('loginForm').onsubmit=async e=>{e.preventDefault();const button=e.submitter;button.disabled=true;$('loginError').textContent='';try{await checked(db.auth.signInWithPassword({email:$('username').value.trim().toLowerCase()+'@nahda-fleet.invalid',password:$('password').value}));await load();$('password').value='';}catch(err){$('loginError').textContent=errorText(err);await db.auth.signOut();}finally{button.disabled=false;}};
 $('logout').onclick=async()=>{await db.auth.signOut();location.reload();};
 $('passwordBtn').onclick=()=>{modal(window.KhotwatiI18n.t('تغيير كلمة المرور'),'<form id="passwordForm">'+field('password',window.KhotwatiI18n.t('كلمة مرور جديدة'),'password','required minlength="6" maxlength="128" autocomplete="new-password"')+field('confirm',window.KhotwatiI18n.t('تأكيد كلمة المرور'),'password','required minlength="6" autocomplete="new-password"')+window.KhotwatiI18n.t('<button class="primary wide">حفظ كلمة المرور</button></form>'));formHandler('passwordForm',async f=>{if(f.get('password')!==f.get('confirm'))throw new Error(window.KhotwatiI18n.t('كلمتا المرور غير متطابقتين'));await checked(db.auth.updateUser({password:f.get('password')}));$('modal').close();toast(window.KhotwatiI18n.t('تم تغيير كلمة المرور'));});};
 $('newCompany').onclick=()=>{modal(window.KhotwatiI18n.t('شركة جديدة وحساب الأدمن'),'<form id="companyForm">'+field('name',window.KhotwatiI18n.t('اسم الشركة'),'text','required maxlength="120"')+field('username',window.KhotwatiI18n.t('اسم مستخدم الأدمن'),'text','required pattern="[a-zA-Z][a-zA-Z0-9_.-]{2,39}" dir="ltr" autocomplete="off"')+field('password',window.KhotwatiI18n.t('كلمة مرور الأدمن'),'password','required minlength="6" maxlength="128" autocomplete="new-password"')+window.KhotwatiI18n.t('<p class="muted">احفظ بيانات الدخول وشاركها مع أدمن الشركة. لا تُرسل رسالة تلقائياً.</p><button class="primary wide">إنشاء الشركة والحساب</button></form>'));formHandler('companyForm',async f=>{const data=Object.fromEntries(f);const r=await api('createCompany',data);$('modal').close();await load();toast(window.KhotwatiI18n.t('تم إنشاء ')+data.name+window.KhotwatiI18n.t(' — اسم المستخدم: ')+r.username);});};
 $('newTrip').onclick=()=>{const active=companies.filter(c=>c.active);if(!active.length){toast(window.KhotwatiI18n.t('أضف شركة فعّالة أولاً'));if(root())switchTab('companies');return;}modal(window.KhotwatiI18n.t('إضافة رحلة سيارة'),window.KhotwatiI18n.t('<form id="tripForm"><div class="form-grid"><div class="full"><label for="f_company">الشركة</label><select id="f_company" name="company_id">')+active.map(c=>'<option value="'+c.id+'">'+esc(c.name)+'</option>').join('')+'</select></div>'+field('plate',window.KhotwatiI18n.t('رقم السيارة'),'text','required maxlength="60"')+field('driver',window.KhotwatiI18n.t('اسم السائق'),'text','maxlength="100"')+field('phone',window.KhotwatiI18n.t('هاتف السائق'),'tel','maxlength="40"')+field('destination',window.KhotwatiI18n.t('الوجهة'),'text','maxlength="140"')+field('declaration_no',window.KhotwatiI18n.t('رقم البيان'),'text','maxlength="80"')+window.KhotwatiI18n.t('</div><button class="primary wide">حفظ الرحلة</button></form>'));formHandler('tripForm',async f=>{const created=await api('createTrip',Object.fromEntries(f));$('modal').close();await load();reportReady=false;await driverAccount(created.trip);toast(window.KhotwatiI18n.t('حُفظت الرحلة. أنشئ حساب السائق أو اربط حساباً موجوداً.'));});};
 $('tripsList').onclick=e=>{const b=e.target.closest('[data-op]');if(b)tripAction(b.dataset.op,b.dataset.id);};
 $('companiesList').onclick=e=>{const b=e.target.closest('[data-company]');if(!b)return;const c=companies.find(x=>x.id===b.dataset.company);if(b.dataset.action==='reset'){modal(window.KhotwatiI18n.t('كلمة مرور أدمن ')+c.name,'<form id="resetForm">'+field('password',window.KhotwatiI18n.t('كلمة مرور جديدة'),'password','required minlength="6" maxlength="128" autocomplete="new-password"')+window.KhotwatiI18n.t('<button class="primary wide">إعادة التعيين</button></form>'));formHandler('resetForm',async f=>{await api('resetCompanyPassword',{company_id:c.id,password:f.get('password')});$('modal').close();toast(window.KhotwatiI18n.t('تم تعيين كلمة المرور الجديدة'));});}else{modal((c.active?window.KhotwatiI18n.t('إيقاف'):window.KhotwatiI18n.t('تفعيل'))+window.KhotwatiI18n.t(' شركة ')+c.name,'<p>'+(c.active?window.KhotwatiI18n.t('سيتوقف دخول الشركة وتحديث روابط سائقيها. تبقى بياناتها محفوظة.'):window.KhotwatiI18n.t('سيعود الوصول للشركة وروابط الرحلات المفتوحة.'))+window.KhotwatiI18n.t('</p><button class="primary wide" id="toggleCompany">تأكيد</button>'));$('toggleCompany').onclick=async()=>{try{await api('setCompanyActive',{company_id:c.id,active:!c.active});$('modal').close();await load();}catch(err){$('modalError').textContent=errorText(err);}};}};
 $('loadReport').onclick=async()=>{try{await makeReport();}catch(e){toast(errorText(e));}};['reportDate','reportCompany'].forEach(id=>$(id).onchange=()=>{reportReady=false;$('reportTable').innerHTML='';$('reportText').value='';$('reportWhatsApp').removeAttribute('href');});
 $('copyReport').onclick=()=>{if(reportReady)copy($('reportText').value);else toast(window.KhotwatiI18n.t('أعد إعداد التقرير أولاً'));};$('printReport').onclick=async()=>{try{await makeReport();window.print();}catch(e){toast(errorText(e));}};
 $('csvReport').onclick=async()=>{try{await makeReport();const safe=s=>'"'+String(s??'').replace(/^[=+@\-\t\r]/,"'$&").replace(/"/g,'""')+'"';const rows=[[window.KhotwatiI18n.t('الشركة'),window.KhotwatiI18n.t('رقم السيارة'),window.KhotwatiI18n.t('المكان'),window.KhotwatiI18n.t('الحالة'),window.KhotwatiI18n.t('آخر تحديث'),window.KhotwatiI18n.t('الملاحظات')],...reportRows.map(t=>[companyName(t.company_id),t.plate,t.place,window.KhotwatiI18n.t(t.status),stamp(t.last_update),t.note])];const blob=new Blob(['\ufeff'+rows.map(r=>r.map(safe).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='fleet-'+$('reportDate').value+'.csv';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){toast(errorText(e));}};
}
async function driver(){ $('login').hidden=true;$('driverPage').hidden=false;$('driverState').innerHTML=options(states);try{const info=await api('driverInfo',{token:driverToken});$('driverPlate').textContent=window.KhotwatiI18n.t('السيارة ')+info.plate;$('driverCompany').textContent=info.company;$('driverDestination').textContent=window.KhotwatiI18n.t('الوجهة: ')+(info.destination||window.KhotwatiI18n.t('غير محدّدة'));$('driverState').value=info.status;}catch(e){$('driverPlate').textContent=window.KhotwatiI18n.t('الرابط غير متاح');$('driverResult').textContent=errorText(e);$('locateDriver').disabled=true;return;}
 $('locateDriver').onclick=()=>{if(!navigator.geolocation){$('gpsStatus').textContent=window.KhotwatiI18n.t('افتح الرابط في متصفح يدعم تحديد الموقع');return;}gps=null;$('sendDriver').disabled=true;$('locateDriver').disabled=true;$('gpsStatus').textContent=window.KhotwatiI18n.t('جارٍ تحديد الموقع…');navigator.geolocation.getCurrentPosition(async p=>{gps={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy,time:Date.now()};$('gpsStatus').textContent=window.KhotwatiI18n.t('تم تحديد الموقع، الدقة نحو ')+Math.round(gps.accuracy)+window.KhotwatiI18n.t(' متر. جارٍ معرفة اسم البلدة…');try{const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),10000);let r;try{r=await fetch('https://api.bigdatacloud.net/data/reverse-geocode-client?latitude='+gps.latitude+'&longitude='+gps.longitude+'&localityLanguage='+window.KhotwatiI18n.language,{signal:controller.signal});}finally{clearTimeout(timer);}if(!r.ok)throw new Error();const d=await r.json();const place=[...new Set([d.locality||d.city,d.principalSubdivision,d.countryName].filter(Boolean))].join(' — ');if(!place)throw new Error();$('driverPlace').value=place;$('gpsStatus').textContent=window.KhotwatiI18n.t('الموقع جاهز. راجع اسم المكان ثم أرسل التحديث.');}catch{$('driverPlace').value='';$('gpsStatus').textContent=window.KhotwatiI18n.t('تم تحديد الإحداثيات، لكن تعذّر معرفة اسم البلدة. اكتب اسمها قبل الإرسال.');}$('locateDriver').disabled=false;$('sendDriver').disabled=false;},e=>{$('gpsStatus').textContent=e.code===1?window.KhotwatiI18n.t('إذن الموقع مرفوض. فعّله لهذا الموقع من إعدادات المتصفح.'):window.KhotwatiI18n.t('تعذّر تحديد الموقع. فعّل خدمة الموقع وحاول مجدداً.');$('locateDriver').disabled=false;},{enableHighAccuracy:true,timeout:20000,maximumAge:0});};
 $('sendDriver').onclick=async()=>{if(!gps||Date.now()-gps.time>5*60000){$('driverResult').textContent=window.KhotwatiI18n.t('حدّد موقعك مجدداً قبل الإرسال');return;}if(!$('driverPlace').value.trim()){$('driverResult').textContent=window.KhotwatiI18n.t('أدخل اسم المكان');return;}$('sendDriver').disabled=true;try{const r=await api('driverUpdate',{token:driverToken,...gps,place:$('driverPlace').value.trim(),status:$('driverState').value,note:$('driverNote').value});$('driverResult').textContent=window.KhotwatiI18n.t('✓ وصل التحديث إلى المكتب — ')+stamp(r.time);gps=null;$('gpsStatus').textContent=window.KhotwatiI18n.t('لإرسال تحديث جديد، حدّد موقعك من جديد.');}catch(e){$('driverResult').textContent=errorText(e);$('sendDriver').disabled=false;}};
}
async function start(){const legacy=new URLSearchParams(location.hash.slice(1)).get('driver')||new URLSearchParams(location.search).get('trip');if(legacy){location.replace('/driver.html?trip='+encodeURIComponent(legacy));return;}if(!window.supabase){$('loginError').textContent=window.KhotwatiI18n.t('تعذّر تحميل تسجيل الدخول؛ حدّث الصفحة.');return;}db=window.supabase.createClient(URL_DB,KEY,{auth:{persistSession:true,storage:window.sessionStorage,autoRefreshToken:true,detectSessionInUrl:false}});bind();driverToken=new URLSearchParams(location.hash.slice(1)).get('driver')||'';if(driverToken){await driver();return;}const {data:{session}}=await db.auth.getSession();if(session){try{await load();}catch(e){$('loginError').textContent=errorText(e);await db.auth.signOut();$('office').hidden=true;$('login').hidden=false;}}}
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_visible_fleet',description:'Read the currently visible trips for the signed-in company account. Does not send messages or change data.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute(input){if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Expected an empty object');if(!me||$('office').hidden)throw new Error('Sign in first');return {role:me.role,trips:visibleTrips().map(t=>({plate:t.plate,company:companyName(t.company_id),place:t.place,status:t.status,lastUpdate:t.last_update}))};}})).catch(()=>{});}catch{}}
window.addEventListener('hashchange',()=>{const token=new URLSearchParams(location.hash.slice(1)).get('driver');if(token)location.assign('/driver.html?trip='+encodeURIComponent(token));});
start().catch(e=>toast(errorText(e)));

let liveOfficeRefresh=false;
setInterval(async()=>{if(liveOfficeRefresh||document.hidden||!me||$('office').hidden||$('modal').open)return;liveOfficeRefresh=true;try{await load();reportReady=false;}catch{}finally{liveOfficeRefresh=false;}},30000);
