# -*- coding: utf-8 -*-
from flask import render_template_string
import web_sporthub_admin_v2 as base

app = base.app

STORE_HTML = r'''<!doctype html>
<html lang="ar" dir="rtl">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>SPORT HUB | متجر الأندية الرياضية</title>
<style>
:root{--bg:#f6f8f6;--ink:#101712;--mut:#69756e;--green:#18b565;--green2:#e9f8ef;--dark:#0d1711;--card:#fff;--line:#e5ebe7;--soft:#f0f4f1;--red:#d34b4b;--shadow:0 18px 50px rgba(13,23,17,.08)}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;font-family:Tahoma,Arial,sans-serif;background:var(--bg);color:var(--ink)}a{text-decoration:none;color:inherit}button,input,select{font:inherit}.wrap{width:min(1180px,calc(100% - 32px));margin:auto}
.topbar{position:sticky;top:0;z-index:30;background:rgba(255,255,255,.94);backdrop-filter:blur(14px);border-bottom:1px solid var(--line)}.topin{height:72px;display:flex;align-items:center;gap:24px}.brand{display:flex;align-items:center;gap:10px;margin-left:auto}.mark{width:42px;height:42px;border-radius:13px;background:var(--dark);display:grid;place-items:center;color:#fff;font-weight:1000}.mark b{color:#62f59a}.brandtxt strong{display:block;font-size:18px}.brandtxt span{font-size:11px;color:var(--mut)}.nav{display:flex;gap:22px;color:#38443e;font-size:13px;font-weight:800}.nav a:hover{color:var(--green)}.cartbtn{border:0;background:var(--dark);color:#fff;border-radius:12px;padding:11px 14px;font-weight:900;cursor:pointer;display:flex;align-items:center;gap:8px}.count{min-width:22px;height:22px;padding:0 6px;border-radius:999px;background:var(--green);display:grid;place-items:center;color:#fff;font-size:11px}
.hero{padding:36px 0 24px}.heroBox{min-height:470px;border-radius:30px;overflow:hidden;background:linear-gradient(135deg,#0c1510,#173622);display:grid;grid-template-columns:1.1fr .9fr;color:#fff;position:relative;box-shadow:var(--shadow)}.heroBox:before{content:"";position:absolute;width:420px;height:420px;border-radius:50%;background:rgba(76,255,136,.10);left:-140px;top:-100px}.heroCopy{padding:70px 60px;position:relative;z-index:2}.eyebrow{display:inline-flex;align-items:center;gap:8px;padding:7px 10px;border-radius:999px;background:rgba(255,255,255,.08);color:#aaf7c6;font-size:11px;font-weight:900}.hero h1{font-size:clamp(42px,6vw,74px);line-height:1.06;margin:20px 0 18px;letter-spacing:-2px}.hero p{color:#bfd0c5;line-height:1.9;font-size:16px;max-width:650px}.heroActions{display:flex;gap:10px;flex-wrap:wrap;margin-top:28px}.primary,.secondary{border:0;border-radius:13px;padding:13px 18px;font-weight:900;cursor:pointer;display:inline-flex;align-items:center;justify-content:center}.primary{background:var(--green);color:#fff}.secondary{background:#fff;color:var(--dark)}.trust{display:flex;gap:18px;flex-wrap:wrap;margin-top:26px;color:#bcd0c3;font-size:12px}.trust span:before{content:"✓";color:#64f79a;margin-left:6px;font-weight:1000}
.heroVisual{display:grid;place-items:center;position:relative}.showcase{width:min(380px,82%);aspect-ratio:1;border-radius:36px;background:linear-gradient(150deg,rgba(255,255,255,.10),rgba(255,255,255,.03));border:1px solid rgba(255,255,255,.12);position:relative;display:grid;place-items:center}.jar{width:175px;height:235px;border-radius:24px 24px 34px 34px;background:linear-gradient(160deg,#fafafa,#cfd7d2);box-shadow:0 35px 80px rgba(0,0,0,.35);transform:rotate(-7deg);position:relative;color:#101712;display:flex;align-items:center;justify-content:center;flex-direction:column}.jar:before{content:"";position:absolute;top:-25px;width:145px;height:38px;border-radius:11px;background:#101712}.jar strong{font-size:28px;letter-spacing:1px}.jar span{font-size:12px;color:#4d5b53;margin-top:5px}.mini{position:absolute;background:#fff;color:#101712;border-radius:16px;padding:12px 14px;box-shadow:var(--shadow);font-size:12px;font-weight:900}.m1{top:55px;right:-20px}.m2{bottom:55px;left:-18px}.mini small{display:block;color:var(--mut);font-weight:500;margin-top:4px}
.section{padding:42px 0}.sectionHead{display:flex;justify-content:space-between;align-items:end;gap:18px;margin-bottom:18px}.sectionHead h2{margin:5px 0 0;font-size:31px}.sectionHead p{margin:0;color:var(--mut);font-size:13px}.label{color:var(--green);font-size:11px;font-weight:1000}.clubs{display:grid;grid-template-columns:repeat(3,1fr);gap:14px}.club{border:1px solid var(--line);background:var(--card);border-radius:20px;padding:18px;display:flex;align-items:center;gap:14px;cursor:pointer;transition:.2s}.club:hover,.club.active{transform:translateY(-2px);border-color:#bfe8cf;box-shadow:var(--shadow)}.clubIcon{width:54px;height:54px;border-radius:16px;background:var(--dark);color:#fff;display:grid;place-items:center;font-weight:1000;font-size:18px;flex:0 0 auto}.club h3{margin:0 0 5px;font-size:15px}.club small{color:var(--mut)}.club .go{margin-right:auto;color:var(--green);font-size:18px}.clubAll{background:linear-gradient(135deg,#f3fff7,#fff)}
.shopBar{display:flex;justify-content:space-between;align-items:center;gap:12px;margin-bottom:18px}.chips{display:flex;gap:8px;overflow:auto;padding-bottom:2px}.chip{white-space:nowrap;border:1px solid var(--line);background:#fff;padding:9px 13px;border-radius:999px;cursor:pointer;font-weight:800;font-size:12px;color:#425047}.chip.active{background:var(--dark);color:#fff;border-color:var(--dark)}.select{border:1px solid var(--line);background:#fff;border-radius:12px;padding:10px 12px;color:#28332d}
.products{display:grid;grid-template-columns:repeat(4,1fr);gap:15px}.product{background:#fff;border:1px solid var(--line);border-radius:22px;overflow:hidden;transition:.2s}.product:hover{transform:translateY(-3px);box-shadow:var(--shadow)}.pvisual{height:220px;background:linear-gradient(180deg,#eff4f1,#e7ede9);display:grid;place-items:center;position:relative}.tag{position:absolute;top:12px;right:12px;background:#fff;padding:6px 9px;border-radius:999px;font-size:10px;font-weight:900;color:#4c5a52;border:1px solid #e4ebe7}.pack{width:105px;height:145px;border-radius:16px 16px 22px 22px;background:linear-gradient(160deg,#fbfbfb,#cbd4cf);box-shadow:0 18px 38px rgba(0,0,0,.14);display:grid;place-items:center;color:#172019;font-weight:1000;text-align:center;padding:10px;transform:rotate(-4deg);position:relative}.pack:before{content:"";position:absolute;top:-15px;width:85px;height:24px;border-radius:7px;background:#16221b}.pack b{font-size:17px}.pack small{display:block;font-size:9px;color:#65736b;margin-top:4px}.pbody{padding:16px}.clubname{font-size:10px;color:var(--green);font-weight:1000}.pbody h3{margin:8px 0 7px;font-size:15px;line-height:1.5}.desc{color:var(--mut);font-size:11px;line-height:1.6;height:36px;overflow:hidden}.pbottom{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:15px}.price{font-size:16px;font-weight:1000}.add{width:40px;height:40px;border-radius:12px;border:0;background:var(--dark);color:#fff;font-size:22px;cursor:pointer}.add:hover{background:var(--green)}
.how{background:#fff;border:1px solid var(--line);border-radius:24px;padding:24px;display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.step{padding:18px;border-radius:18px;background:var(--soft)}.num{width:34px;height:34px;border-radius:10px;background:var(--dark);color:#fff;display:grid;place-items:center;font-weight:1000;margin-bottom:14px}.step h3{margin:0 0 7px;font-size:15px}.step p{margin:0;color:var(--mut);font-size:12px;line-height:1.7}.footer{margin-top:35px;background:var(--dark);color:#fff;padding:34px 0}.footin{display:flex;justify-content:space-between;gap:20px;align-items:center}.footin p{color:#9eb2a6;font-size:12px;max-width:600px;line-height:1.8}
.overlay{position:fixed;inset:0;background:rgba(7,14,10,.46);z-index:50;opacity:0;pointer-events:none;transition:.2s}.overlay.open{opacity:1;pointer-events:auto}.drawer{position:fixed;top:0;left:0;width:min(450px,100%);height:100vh;background:#fff;z-index:60;transform:translateX(-100%);transition:.28s;display:flex;flex-direction:column;box-shadow:30px 0 80px rgba(0,0,0,.18)}.drawer.open{transform:none}.dhead{padding:18px 20px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.dhead h2{margin:0}.x{border:0;background:var(--soft);width:38px;height:38px;border-radius:11px;font-size:21px;cursor:pointer}.dcontent{flex:1;overflow:auto;padding:10px 20px}.empty{padding:60px 20px;text-align:center;color:var(--mut)}.cartline{display:grid;grid-template-columns:1fr auto;gap:10px;padding:14px 0;border-bottom:1px solid var(--line)}.cartline h4{margin:0 0 5px;font-size:14px}.cartline small{color:var(--mut)}.qty{display:flex;align-items:center;gap:7px}.qty button{width:29px;height:29px;border-radius:9px;border:1px solid var(--line);background:#fff;cursor:pointer}.remove{border:0;background:none;color:var(--red);font-size:11px;padding:0;margin-top:7px;cursor:pointer}.dfoot{padding:18px 20px;border-top:1px solid var(--line)}.total{display:flex;justify-content:space-between;font-size:18px;margin-bottom:12px}.full{width:100%}
.checkout{display:none;margin-top:16px;padding-top:16px;border-top:1px solid var(--line)}.field{display:block;margin:10px 0;font-size:11px;color:var(--mut);font-weight:800}.field input{width:100%;margin-top:6px;padding:11px;border:1px solid #d8e2dc;border-radius:11px;outline:none}.field input:focus{border-color:#8dd9ac;box-shadow:0 0 0 3px #e6f8ed}.paygroup{margin:14px 0;padding:14px;border-radius:15px;background:#f7faf8;border:1px solid var(--line)}.paytop{display:flex;justify-content:space-between;gap:10px;align-items:center}.paytop b{font-size:14px}.paytop span{font-weight:1000}.qrimg{width:145px;max-width:100%;background:#fff;padding:7px;border-radius:12px;border:1px solid var(--line);display:block;margin:12px auto}.noqr{text-align:center;padding:14px;color:var(--mut);font-size:11px}.notice{display:none;margin:10px 0;background:var(--green2);color:#1c6c43;padding:11px;border-radius:11px;font-size:12px;line-height:1.7}.toast{position:fixed;bottom:22px;right:22px;z-index:100;background:#122019;color:#fff;padding:11px 15px;border-radius:12px;opacity:0;transform:translateY(10px);pointer-events:none;transition:.2s;font-size:12px}.toast.show{opacity:1;transform:none}
@media(max-width:980px){.heroBox{grid-template-columns:1fr}.heroVisual{display:none}.products{grid-template-columns:repeat(3,1fr)}.clubs{grid-template-columns:1fr 1fr}.nav{display:none}.heroCopy{padding:55px 35px}}
@media(max-width:720px){.products{grid-template-columns:repeat(2,1fr)}.clubs{grid-template-columns:1fr}.how{grid-template-columns:1fr}.sectionHead{display:block}.sectionHead p{margin-top:7px}.shopBar{align-items:stretch;flex-direction:column}.footin{display:block}.hero h1{font-size:44px}.heroCopy{padding:42px 24px}.topin{height:64px}.brandtxt span{display:none}.products{gap:10px}.pvisual{height:180px}}
@media(max-width:430px){.wrap{width:min(100% - 22px,1180px)}.products{grid-template-columns:1fr 1fr}.pbody{padding:12px}.pvisual{height:160px}.pack{width:82px;height:115px}.hero h1{font-size:38px}.hero p{font-size:14px}.secondary{display:none}}
</style>
</head>
<body>
<header class="topbar"><div class="wrap topin"><a class="brand" href="#"><div class="mark"><b>S</b>H</div><div class="brandtxt"><strong>SPORT HUB</strong><span>متجر الأندية الرياضية</span></div></a><nav class="nav"><a href="#clubs">الأندية</a><a href="#shop">المنتجات</a><a href="#payment">طريقة الدفع</a></nav><button class="cartbtn" onclick="openCart()">السلة <span class="count" id="count">0</span></button></div></header>
<main>
<section class="hero"><div class="wrap"><div class="heroBox"><div class="heroCopy"><span class="eyebrow">منصة رياضية • دفع شام كاش</span><h1>كل منتجات ناديك<br>بمكان واحد.</h1><p>اختر ناديك، تصفّح المنتجات، وادفع مباشرة إلى حساب شام كاش الخاص بالنادي بطريقة واضحة وسريعة.</p><div class="heroActions"><a class="primary" href="#shop">تسوّق الآن</a><a class="secondary" href="#clubs">اختيار النادي</a></div><div class="trust"><span>دفع مباشر للنادي</span><span>طلبات محفوظة</span><span>متوافق مع الموبايل</span></div></div><div class="heroVisual"><div class="showcase"><div class="jar"><strong>WHEY</strong><span>SPORT NUTRITION</span></div><div class="mini m1">منتجات أصلية<small>مرتبطة بالنادي</small></div><div class="mini m2">شام كاش<small>QR مستقل لكل نادي</small></div></div></div></div></div></section>
<section class="section" id="clubs"><div class="wrap"><div class="sectionHead"><div><span class="label">اختر ناديك</span><h2>الأندية المشاركة</h2></div><p>اضغط على النادي لعرض منتجاته فقط.</p></div><div class="clubs" id="clubsGrid"></div></div></section>
<section class="section" id="shop"><div class="wrap"><div class="sectionHead"><div><span class="label">المتجر</span><h2>المنتجات الرياضية</h2></div><p id="resultText">كل المنتجات المتاحة</p></div><div class="shopBar"><div class="chips" id="chips"><button class="chip active" data-cat="">الكل</button><button class="chip" data-cat="protein">بروتين</button><button class="chip" data-cat="creatine">كرياتين</button><button class="chip" data-cat="supplements">مكملات</button><button class="chip" data-cat="accessories">إكسسوارات</button><button class="chip" data-cat="apparel">ملابس</button></div><select class="select" id="clubFilter" onchange="renderProducts()"><option value="">كل الأندية</option></select></div><div class="products" id="productsGrid"></div></div></section>
<section class="section" id="payment"><div class="wrap"><div class="sectionHead"><div><span class="label">طريقة الدفع</span><h2>بسيطة وواضحة</h2></div></div><div class="how"><div class="step"><div class="num">1</div><h3>اختر المنتجات</h3><p>أضف المنتجات إلى السلة من أي نادي مشارك.</p></div><div class="step"><div class="num">2</div><h3>ادفع عبر شام كاش</h3><p>يظهر لك QR وحساب شام كاش الخاص بالنادي مع المبلغ المطلوب.</p></div><div class="step"><div class="num">3</div><h3>سجّل رقم العملية</h3><p>أدخل رقم عملية شام كاش حتى يتمكن النادي من التحقق من الدفع وتجهيز الطلب.</p></div></div></div></section>
</main>
<footer class="footer"><div class="wrap footin"><div><strong>SPORT HUB</strong><p>منصة تجمع متاجر الأندية الرياضية وتفصل منتجات ومدفوعات كل نادي بشكل مستقل.</p></div><div style="color:#9eb2a6;font-size:12px">الدفع عبر شام كاش</div></div></footer>
<div class="overlay" id="overlay" onclick="closeCart()"></div><aside class="drawer" id="drawer"><div class="dhead"><h2>سلة المشتريات</h2><button class="x" onclick="closeCart()">×</button></div><div class="dcontent"><div id="cartLines"></div><div class="checkout" id="checkout"><h3 style="margin:6px 0 12px">بيانات الطلب</h3><label class="field">الاسم الكامل<input id="name" placeholder="اسم العميل"></label><label class="field">رقم الهاتف<input id="phone" placeholder="09xxxxxxxx"></label><label class="field">العنوان<input id="address" placeholder="المدينة / المنطقة"></label><div id="payments"></div><div class="notice" id="notice"></div><button class="primary full" onclick="placeOrder()">تسجيل الطلب</button></div></div><div class="dfoot"><div class="total"><span>الإجمالي</span><b id="total">0 ل.س</b></div><button id="goPay" class="primary full" onclick="showCheckout()">متابعة للدفع</button></div></aside><div class="toast" id="toast"></div>
<script>
let clubs=[],products=[],cart={},activeCat='';
const money=n=>new Intl.NumberFormat('ar-SY').format(n)+' ل.س';
const shortCat=c=>({protein:'PROTEIN',creatine:'CREATINE',supplements:'SUPPLEMENTS',accessories:'GEAR',apparel:'SPORT WEAR',other:'SPORT'})[c]||'SPORT';
function toast(t){let el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1500)}
async function boot(){try{clubs=await (await fetch('/sporthub/api/clubs')).json();products=await (await fetch('/sporthub/api/products')).json();renderClubs();renderProducts();renderCart()}catch(e){document.getElementById('productsGrid').innerHTML='<div class="empty">تعذر تحميل المنتجات حالياً.</div>'}}
function renderClubs(){let g=document.getElementById('clubsGrid'),f=document.getElementById('clubFilter');g.innerHTML=`<div class="club clubAll active" data-club=""><div class="clubIcon">ALL</div><div><h3>كل الأندية</h3><small>عرض جميع المنتجات</small></div><div class="go">←</div></div>`;clubs.forEach(c=>{let initials=c.name.split(/\s+/).map(x=>x[0]).join('').slice(0,2);g.innerHTML+=`<div class="club" data-club="${c.id}"><div class="clubIcon">${initials||'GY'}</div><div><h3>${c.name}</h3><small>${c.city||'نادي رياضي'}</small></div><div class="go">←</div></div>`;f.innerHTML+=`<option value="${c.id}">${c.name}</option>`});g.querySelectorAll('.club').forEach(el=>el.onclick=()=>{g.querySelectorAll('.club').forEach(x=>x.classList.remove('active'));el.classList.add('active');f.value=el.dataset.club;renderProducts();document.getElementById('shop').scrollIntoView({behavior:'smooth'})})}
function renderProducts(){let cf=document.getElementById('clubFilter').value,g=document.getElementById('productsGrid');let rows=products.filter(p=>(!cf||String(p.club_id)===cf)&&(!activeCat||p.category===activeCat));document.getElementById('resultText').textContent=rows.length?`${rows.length} منتج متاح`:'لا توجد منتجات ضمن هذا الاختيار';g.innerHTML='';rows.forEach(p=>{g.innerHTML+=`<article class="product"><div class="pvisual"><span class="tag">${p.stock_qty>0?'متوفر':'غير متوفر'}</span><div class="pack"><div><b>${shortCat(p.category)}</b><small>${p.club_name}</small></div></div></div><div class="pbody"><span class="clubname">${p.club_name}</span><h3>${p.name}</h3><div class="desc">${p.description||'منتج رياضي متوفر عبر النادي.'}</div><div class="pbottom"><div class="price">${money(p.price_syp)}</div><button class="add" ${p.stock_qty<=0?'disabled style="opacity:.35"':''} onclick="add(${p.id})">+</button></div></div></article>`});if(!rows.length)g.innerHTML='<div class="empty" style="grid-column:1/-1">لا توجد منتجات حالياً.</div>'}
document.getElementById('chips').querySelectorAll('.chip').forEach(b=>b.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));b.classList.add('active');activeCat=b.dataset.cat;renderProducts()});
function add(id){cart[id]=(cart[id]||0)+1;renderCart();toast('تمت إضافة المنتج للسلة')}
function changeQty(id,d){cart[id]=(cart[id]||0)+d;if(cart[id]<=0)delete cart[id];renderCart()}
function removeItem(id){delete cart[id];renderCart()}
function renderCart(){let box=document.getElementById('cartLines'),tot=0,cnt=0;box.innerHTML='';Object.entries(cart).forEach(([id,q])=>{let p=products.find(x=>x.id==id);if(!p)return;tot+=p.price_syp*q;cnt+=q;box.innerHTML+=`<div class="cartline"><div><h4>${p.name}</h4><small>${p.club_name} • ${money(p.price_syp)}</small><button class="remove" onclick="removeItem(${p.id})">حذف</button></div><div class="qty"><button onclick="changeQty(${p.id},-1)">−</button><b>${q}</b><button onclick="changeQty(${p.id},1)">+</button></div></div>`});if(!cnt)box.innerHTML='<div class="empty">السلة فارغة حالياً.</div>';document.getElementById('count').textContent=cnt;document.getElementById('total').textContent=money(tot);document.getElementById('goPay').style.display=cnt?'block':'none';if(!cnt)document.getElementById('checkout').style.display='none'}
function openCart(){document.getElementById('drawer').classList.add('open');document.getElementById('overlay').classList.add('open')}function closeCart(){document.getElementById('drawer').classList.remove('open');document.getElementById('overlay').classList.remove('open')}
function showCheckout(){if(!Object.keys(cart).length)return;document.getElementById('checkout').style.display='block';document.getElementById('goPay').style.display='none';let groups={};Object.entries(cart).forEach(([id,q])=>{let p=products.find(x=>x.id==id);groups[p.club_id]=(groups[p.club_id]||0)+p.price_syp*q});let b=document.getElementById('payments');b.innerHTML='<h3 style="margin:18px 0 8px">الدفع عبر شام كاش</h3>';Object.entries(groups).forEach(([cid,amt])=>{let c=clubs.find(x=>x.id==cid);b.innerHTML+=`<div class="paygroup"><div class="paytop"><b>${c.name}</b><span>${money(amt)}</span></div>${c.qr_url?`<img class="qrimg" src="${c.qr_url}" alt="QR شام كاش">`:`<div class="noqr">لم يضف النادي QR شام كاش بعد.</div>`}<div style="font-size:11px;color:#69756e">حساب شام كاش: <b style="color:#101712">${c.shamcash_account||'غير محدد'}</b></div><label class="field">رقم عملية شام كاش<input data-tx="${cid}" placeholder="أدخل رقم العملية بعد الدفع"></label><label class="field">صورة الإيصال - اختياري<input type="file" accept="image/*" data-receipt="${cid}"></label></div>`});document.getElementById('checkout').scrollIntoView({behavior:'smooth',block:'start'})}
function file64(inp){return new Promise(res=>{if(!inp||!inp.files||!inp.files[0])return res(null);let r=new FileReader();r.onload=()=>res(r.result);r.readAsDataURL(inp.files[0])})}
async function placeOrder(){let name=document.getElementById('name').value.trim(),phone=document.getElementById('phone').value.trim(),notice=document.getElementById('notice');if(!name||!phone){notice.style.display='block';notice.textContent='أدخل الاسم ورقم الهاتف أولاً.';return}let items=Object.entries(cart).map(([id,q])=>({product_id:+id,qty:q}));let pay=[];for(let inp of document.querySelectorAll('[data-tx]')){let cid=+inp.dataset.tx,receipt=await file64(document.querySelector(`[data-receipt="${cid}"]`));pay.push({club_id:cid,transaction:inp.value.trim(),receipt})}let r=await fetch('/sporthub/api/orders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({customer_name:name,phone,address:document.getElementById('address').value.trim(),items,payments:pay})});let j=await r.json();notice.style.display='block';if(!r.ok){notice.textContent=j.error||'تعذر تسجيل الطلب.';return}notice.innerHTML=`تم تسجيل الطلب بنجاح. رقم الطلب: <b>${j.order_no}</b><br>حالة الدفع: بانتظار التحقق.`;cart={};renderCart()}
boot();
</script>
</body></html>'''

def premium_storefront():
    return render_template_string(STORE_HTML)

app.view_functions['sporthub_home'] = premium_storefront
